### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #2

# Iteration

ตัวอย่างของ iteration ที่เห็นได้บ่อยที่สุดคือการใช้ `for` loop

In [6]:
#Range

myrange = range(1, 10, 2)

for i in myrange:
  print(i)

1
3
5
7
9


In [4]:
#List
mylist = [1, 3, 5, 7, 9]

for i in mylist:
  print(i)

1
3
5
7
9


## `enumerate`

สมมติว่าข้างล่างนี้คือตัวอย่างของการทำนาย time series ใน 0-9 วันข้างหน้า

In [7]:
forecast = [34, 62, 21, 87, 95, 21, 42, 17, 39, 23]

for i, value in enumerate(forecast):
  print(f"Day {i} - {value}")

Day 0 - 34
Day 1 - 62
Day 2 - 21
Day 3 - 87
Day 4 - 95
Day 5 - 21
Day 6 - 42
Day 7 - 17
Day 8 - 39
Day 9 - 23


## Iterator

อีกวิธีหนึ่งในการสร้าง loop นอกจากการใช้ `range` หรือ `list` แล้ว เราสามารถสร้าง `iterator` โดยใช้ฟังก์ชัน `iter` ครอบ `list` ของสิ่งที่เราอยากจะให้วน loop ไปเรื่อย ๆ

In [16]:
#iter

#current_number = [0, 1, 2, 3, 4] # list นี้ยังไม่สามารถดึงตัวเลขมานอก for loop ได้

current_number = iter([0, 1, 2, 3, 4]) # สร้าง iterator

In [21]:
#next

next(current_number) # ลองรันคำสัง่นี้ไปเรื่อยๆ ดู


4

## ใช้ Iterator ใน for loop

In [23]:
# for loop

current_number = iter([2, 4, 6, 8])

for i in current_number:
  print(i)

2
4
6
8


In [24]:
# another way

current_number = iter([2, 4, 6, 8])

next(current_number) # ถ้าใช้คำสั่ง next ด้วย

for i in current_number:
  print(i)

4
6
8


In [27]:
# another way

current_number = iter([2, 4, 6, 8])

for i in range(4):
  print(next(current_number))

2
4
6
8


## Convert Iterator to List

In [28]:
current_number = iter([2, 4, 6, 8])

my_list = list(current_number)

my_list

[2, 4, 6, 8]

## `zip`

บางครั้งเราต้องการวน loop ตาม items ในหลายๆ list พร้อมกัน ตัวอย่างเช่นชื่อ สัญชาติ และสาขาของนักวิจัย 12 ท่านข้างล่างนี้

In [144]:
names = [
    'Frances Arnold', 'George Smith', 'Gregory Winter',
    'Denis Mukwege', 'Nadia Murad'
]

nationalities = [
    'USA', 'USA', 'UK',
    'DRC', 'Iraq'
]

categories = [
    'Chemistry', 'Chemistry', 'Chemistry',
    'Peace', 'Peace'
]

In [145]:
#zip

scientists = zip(names, nationalities, categories)

In [146]:
next(scientists)

('Frances Arnold', 'USA', 'Chemistry')

In [147]:
#print
#for name, national, category in zip(names, nationalities, categories):
for name, national, category in scientists:
  print(f"{name} is a {category} from {national}")

('George Smith', 'USA', 'Chemistry')
('Gregory Winter', 'UK', 'Chemistry')
('Denis Mukwege', 'DRC', 'Peace')
('Nadia Murad', 'Iraq', 'Peace')


The output of each `next` call on a zip object is a **tuple**.

In [ ]:
#next

In [149]:
#for loop

for

## Convert to list

In [43]:
scientists = zip(names, nationalities, categories)

list(scientists)

[('Frances Arnold', 'USA', 'Chemistry'),
 ('George Smith', 'USA', 'Chemistry'),
 ('Gregory Winter', 'UK', 'Chemistry'),
 ('Denis Mukwege', 'DRC', 'Peace'),
 ('Nadia Murad', 'Iraq', 'Peace')]

## Convert to Dict

In [44]:
items = ["pen", "paper", "pencil", "eraser"]
prices = [12, 1, 7, 9]

dict(zip(items, prices))

{'pen': 12, 'paper': 1, 'pencil': 7, 'eraser': 9}

In [45]:
dict(zip(prices, items))

{12: 'pen', 1: 'paper', 7: 'pencil', 9: 'eraser'}

## ใช้ `zip` กับ iterator

In [46]:
items = iter(["pen", "paper", "pencil", "eraser"])
prices = iter([12, 1, 7, 9])

for item, price in zip(items, prices):
  print(f"Item: {item}, Price: {price}")

Item: pen, Price: 12
Item: paper, Price: 1
Item: pencil, Price: 7
Item: eraser, Price: 9


# Errors and Exception handling

## SyntaxError

เกิดขึ้นในกรณีที่โค้ดมี format ที่ไม่ถูกต้องตามหลักการของ python หรือว่ามีโค้ดบางส่วนที่ขาดหายไป

In [47]:
my_list = [1,2,3

SyntaxError: incomplete input (<ipython-input-47-3847fd62f216>, line 1)

In [48]:
for i in range(5)
    print(i)

SyntaxError: expected ':' (<ipython-input-48-e309b1f0aa1c>, line 1)

In [49]:
import numpy as np

my_list = [2, 65, 82, 13, 845, 84, 265, 97, 43]

variance = np.sum(np.array(my_list) - np.mean(my_list)**2/(len(my_list) - 1)

print(variance)

SyntaxError: '(' was never closed (<ipython-input-49-5424660e29c4>, line 5)

## RuntimeError

เกิดขึ้นในกรณีที่โค้ดผ่านการเช็ค format ผ่าน แต่เกิดปัญหาขึ้นตอนรันโค้ด

### 1. TypeError

In [50]:
print(4 + "Kings") #5print("4"+ "Kings")

TypeError: unsupported operand type(s) for +: 'int' and 'str'

### 2. IndexError

In [51]:
mylist = [1, 2, 3, 4]
print(mylist[4]) #เรามี index แค่ 0, 1, 2, 3

IndexError: list index out of range

In [54]:
import numpy as np

myarray = np.array([[1, 2],
                    [3, 4]])
myarray[2,2] #myarray[1,1]

IndexError: index 2 is out of bounds for axis 0 with size 2

### 3. KeyError

In [55]:
mydict = {'Will': 14, 'Lucas': 14, 'Dustin': 14}

mydict["Mike"]

KeyError: 'Mike'

### 4. NameError

In [56]:
import pandas as pd

X = pd.read_csv(sample_data/mnist_test.csv)
#X = pd.read_csv("sample_data/mnist_test.csv")

NameError: name 'sample_data' is not defined

### 5. IndentationError

In [60]:
for num in [1,2,3,4]:
print(num) #IndentationError

IndentationError: expected an indented block after 'for' statement on line 1 (<ipython-input-60-ce90638ba640>, line 2)

In [62]:
for num in [1,2,3,4]:
  for word in ['one', 'two', 'three']:
  print(num)

IndentationError: expected an indented block after 'for' statement on line 2 (<ipython-input-62-7e9b34a73c98>, line 3)

### 6. OverflowError

In [63]:
x = 10.0

print(x**309)

OverflowError: (34, 'Numerical result out of range')

In [64]:
x = 10

print(x**309)

1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000


วิธีการหาและแก้ bug ใน python

1. หา line ที่มี error

  ใส่ `print` ลงไปในที่ต่างๆ ของโค้ดเพื่อหาจุดผิด

2. ถ้าไม่เคยเห็น error ชนิดนั้นมาก่อน หรือไม่รู้วิธีแก้ไข ลองนำ error กับชื่อ package ที่ใช้ไปค้นหาใน google ว่าเคยมีคนที่เคยเจอปัญหาเหมือนกันหรือไม่





In [ ]:
import numpy as np

num = (1,2,3,4,5,6,7)

np.mean(num)

## Exercise 1: ใช้ `zip` เพื่อสร้าง List ที่มี tuple ของ movie ID และ movie name เรื่องต่างๆ

In [65]:
lst1 = ["Toy Story", "Transformers", "Star Wars", "Titanic"]
lst2 = [1, 45366, 2451, 132]

movie_id_name = list(zip(lst1, lst2)) #TODO: your code here

print(movie_id_name)

[('Toy Story', 1), ('Transformers', 45366), ('Star Wars', 2451), ('Titanic', 132)]


## Exercise 2: แก้ error ในโค้ดข้างล่างนี้

1.

In [77]:
authors = { #authrs
    "Charles Dickens": "1870",
    "William Thackeray": "1863",
    "Anthony Trollope": "1882",
    "Gerard Manley Hopkins": "1889"} #ลืมปิดด้วยฟันหนู

for author, date in authors.items(): #ลืมใส่ comma
    print(f"{author} died in {date}")

Charles Dickens died in 1870
William Thackeray died in 1863
Anthony Trollope died in 1882
Gerard Manley Hopkins died in 1889


2.

In [86]:
year = int(input("What year were you born? ")) # == และ int.input และ '))

if year <= 1996: #ลืมโคลอน:
    print("You are a Millennial!")
elif year > 1996 & year < 2012: #&& มีสองตัว
    print("You are a Zoomer!")
else: #elif แก้เป็น else
    print("You are an Alpha!")

What year were you born? 2003
You are a Zoomer!


3.

In [104]:
class Person:
  def __init__(self, first_name, last_name): #init เป็น __init__
    self.first = first_name
    self.last = last_name #last_nme
  def speak(self):
    print("My name is", self.first + " " + self.last) # indent ผิดช่อง และ "My name is + " เป็น "My name is"

me = Person("Timothee", "Chalamet")
you = Person("Jennifer", "Lawrence")

me.speak() # ลืมเติม ()
you.speak() # ลืมเติม ()

My name is Timothee Chalamet
My name is Jennifer Lawrence


4. ฟังก์ชัน `minimum` มี input เป็น `list` ใช้ในการหาสมาชิกที่ต่ำที่สุดใน `list` นั้น แต่พอลองทดสอบฟังก์ชันข้างล่างพบว่า output ไม่เป็นไปตามที่คาดหวังไว้ จงแก้ไขฟังก์ชันให้ถูกต้อง

In [106]:
def minimum(some_list):
    a = 0
    for x in range(1, len(some_list)):
        if some_list[x] < a:
            a = some_list[x]
    return a

minimum([76,31,90,39,12])

0

In [108]:
#แก้ไขฟังก์ชัน
def minimum(some_list):
    a = some_list[0]
    for x in some_list:
        if x < a:
            a = x
    return a

minimum([76,31,90,39,12])

12

5. แก้โค้ดข้างล่างต่อไปนี้ เพื่อแสดงผลอุณหภูมิในแต่ละเดือนตั้งแต่เดือนมกราคม (Jan) ถึงเดือนธันวาคม (Dec)

In [113]:
months = iter(["Jan", "Feb", "Mar", "Apr", #แก้ "Jun" เป็น "Jan"
          "May", "Jun", "Jul", "Aug",
          "Sep", "Oct", "Nov", "Dec"])
temps = iter([27, 28, 30, 31, 30, 30, 30, 30, 29, 29, 28, 26])

months_temps = zip(months, temps) #ขาดคำว่า zip

for i in range(12):
  month, temp = next(months_temps)
  print(f"Average temperature in {month} is {temp}C")

Average temperature in Jan is 27C
Average temperature in Feb is 28C
Average temperature in Mar is 30C
Average temperature in Apr is 31C
Average temperature in May is 30C
Average temperature in Jun is 30C
Average temperature in Jul is 30C
Average temperature in Aug is 30C
Average temperature in Sep is 29C
Average temperature in Oct is 29C
Average temperature in Nov is 28C
Average temperature in Dec is 26C


6. สมมติว่าเรามี array สองตัวคือ

`x = [1, 2, 3]` และ `y = [[4, 5, 6], [7, 8, 9]]`

ต้องการนำ `x` และ `y` มาต่อกันให้ได้ array ที่มีขนาด 3x3 ดังนี้:

`[[1, 2, 3], [4, 5, 6], [7, 8, 9]]`

ด้วยการใช้ฟังก์ชัน `np.concatenate` ([reference](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html)) แต่ว่าลองรันโค้ดข้างล่างแล้วเกิด error ขึ้นมา

ลองทำการศึกษา reference ที่ให้ไว้ข้างบนและลองใช้ google เพื่อหาวิธีในการแก้ error ในโค้ดข้างล่างนี้

In [127]:
import numpy as np

x = np.array([[1, 2, 3]]) #ต้องทำให้เป็น 2 มิติ เพิ่ม []
y = np.array([[4, 5, 6],[7, 8, 9]])

result = np.concatenate((x,y), axis = 0)
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


อย่าลืม log out gmail หลังทำปฏิบัติการเสร็จสิ้น